{
  "HTML": {
    "beautifiers": [
      "Pretty Diff",
      "JS-Beautify"
    ],
    "end_with_newline": true,
    "force_indentation": true,
    "indent_comments": true,
    "indent_scripts": "normal",
    "indent_size": 4,
    "indent_style": "space",
    "max_preserve_newlines": 0
    "wrap_attributes": "auto",
    "wrap_attributes_indent_size": 0,
    "wrap_line_length": 100
  }
}