# Generated by Django 4.2 on 2023-04-15 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="general.topic",
            ),
        ),
    ]
