# Generated by Django 4.1.7 on 2023-03-22 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("general", "0002_Room2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="participants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
