# Generated by Django 4.2 on 2023-05-19 21:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="products",
        ),
        migrations.AlterField(
            model_name="cart",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
