# Generated by Django 4.2 on 2023-05-26 00:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0006_alter_customer_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-placed_at"],
                "permissions": [("cancel_order", "Can cancel order")],
            },
        ),
    ]
