# Generated by Django 4.2 on 2023-06-03 02:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_alter_order_options_alter_customer_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["user__first_name", "user__last_name"],
                "permissions": [("view_history", "Can view history")],
            },
        ),
    ]
